services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}

  front:
    build: ./front
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://api:3000
    volumes:
      - ./front/src:/usr/src/app/src
      - ./front/config:/usr/src/app/config
      - ./front/next.config.mjs:/usr/src/app/next.config.mjs
      - /usr/src/app/node_modules
      - /usr/src/app/.next


  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
