services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
  front:
    build: ./front
    ports:
      - "3001:3000"
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/.next
      - /usr/src/app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3000
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
